// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingManagementSystem.Infrastructure;

#nullable disable

namespace ParkingManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120023231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingManagementSystem.Models.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Long")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sites", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c8d24cf-0f3c-4d3f-8014-0b44b0cbbc43"),
                            Lat = "40.7128 N",
                            Long = "74.0060 W",
                            Name = "Site A"
                        },
                        new
                        {
                            Id = new Guid("4f0c3b03-2b0b-4a13-b4f2-3aa5e66d0c42"),
                            Lat = "51.5074 N",
                            Long = "0.1278 W",
                            Name = "Site B"
                        },
                        new
                        {
                            Id = new Guid("5f0c3b03-3b0b-4a13-b4f2-3aa5e66d0c42"),
                            Lat = "55.5074 N",
                            Long = "65.1278 W",
                            Name = "Site C"
                        });
                });

            modelBuilder.Entity("ParkingManagementSystem.Models.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdditionalHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FirstHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Tariffs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f0c3b03-9b0b-4a13-b4f2-3aa5e66d0c42"),
                            AdditionalHour = 3.00m,
                            FirstHour = 5.00m,
                            SiteId = new Guid("7c8d24cf-0f3c-4d3f-8014-0b44b0cbbc43")
                        },
                        new
                        {
                            Id = new Guid("8f0c3b03-9b0b-4a13-b4f2-3aa5e66d0c42"),
                            AdditionalHour = 4.00m,
                            FirstHour = 6.00m,
                            SiteId = new Guid("4f0c3b03-2b0b-4a13-b4f2-3aa5e66d0c42")
                        });
                });

            modelBuilder.Entity("ParkingManagementSystem.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsExtend")
                        .HasColumnType("bit");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TariffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("TariffId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("ParkingManagementSystem.Models.Tariff", b =>
                {
                    b.HasOne("ParkingManagementSystem.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ParkingManagementSystem.Models.Ticket", b =>
                {
                    b.HasOne("ParkingManagementSystem.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingManagementSystem.Models.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Site");

                    b.Navigation("Tariff");
                });
#pragma warning restore 612, 618
        }
    }
}
